export interface StudentWithId{
    StudentId: number,
    FirstName: string,
    LastName: string,
    ContactNo: string,
    Email: string,
    Ssn: number,
    Dob: Date,
    Title: string,
    StartDate: Date,
    ContactPersonName: string,
    ContactPersonNumber: string,
    PrimaryAdressLine: string,
    Street: string,
    City: string,
    Country: string,
} 